on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    concurrency: production
    steps:
      - name: Init
        uses: actions/checkout@v4
      - name: Init Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache Node Modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy Build
        run: cp -rf ./build ${{secrets.BOXY_WWW_DIRECTORY}}
      - name: Restart Container
        run: echo ${{secrets.ACCOUNT_PASSWORD}} | sudo -S docker restart swrigdon
